### ISSUE TITLE
Testing on 1.1 RC2

### ISSUE THREAD

**Issue by fourroses666** [Deesen/ckeditor4-modx-evo#3]
I have installed it on 1.1 RC2. Works. Mini works too.
- Insert link doesn't work. I don't see the popup, just the background transparency. 
  (I really like the linklist)
- The icon buttons/options, can we determined that somewhere which are shown?
- I noticed some weird // // on all resources and on the Config > Interface page. 
- Maybe we can dropdown select different skins?
- When TinyMCE is default and on a resource and select CKEditor below the Content field I get all icon options/buttons. See img below. Its good when CKEditor is default. 

Good to see people improving Evo!

![img](https://cloud.githubusercontent.com/assets/523389/13215486/e87b1386-d955-11e5-9947-8c9a270943e5.png)

If you would like to see it I can give manager login for my demo version.

**Comment by Deesen** [comment]
Thanks for testing! I try to answer quick:
- Insert link: This is strange, I have no clue. I need access to your demo then indeed.
- The icon buttons/options: Yes you have the same templates (called themes) in Modx-configuration (below TinyMCE settings) available for CK4 like for Tiny3. And you can create your own themes easily. For that check the directory ckeditor4/themes. I commented almost every CK-parameter with link to official docs. The buttons-list you can find here http://ckeditor.com/comment/123266#comment-123266
- Weird //: In plugin-code you pasted into manager remove the first line //<?php
- Dropdown select different skins: You can select already each theme of directory ckeditor4/theme/ and each skin in ckeditor4/skin/ within Modx-configuration.
- get all icon options/buttons: You need to set a different theme to modify toolbar in Modx-configuration. Default is "Full theme". You can also set theme to custom and use Modx-configurations "Custom-Toolbar-Params" to change toolbar (using the CK-Buttonslist above)
- Its good when CKEditor is default: -> set it default in Modx-configuration

**Comment by fourroses666** [comment]
- I have given you access. If you have spare time you can have a look. 
  _I tried theme ModxRE but the same issue with the "Insert Link" popup._
- Will have a look at custom editor, like to setup that myself _(and keep that even after update)_
- The // are gone now after removing //<php?

oke to the others ;0

**Comment by Deesen** [comment]
Thanks for access!
- Link-Button: I forgot to update CK-language-files. You need to replace nl.js (or better all lang-files), then it should work:
  https://github.com/Deesen/ckeditor4-modx-evo/tree/master/assets/plugins/ckeditor4/ckeditor/lang
- The // are gone now after removing //<php?  YES ;-)

**Comment by fourroses666** [comment]
Hmm, updated whole package but it seems to work with Chrome but FF it doesn't. No popup when clicking "Insert link" (I'm on WIN7 and FF 44.02)

**Comment by fourroses666** [comment]
Ah nevermind it works now, guess some cache issue :)

**Comment by fourroses666** [comment]
I really like the Link-list in TinyMCE.
Or the search in TinyMCE4.
![linklist](https://cloud.githubusercontent.com/assets/523389/13284656/f10ed36a-daf5-11e5-911a-9d54a94469c2.png)
![search](https://cloud.githubusercontent.com/assets/523389/13284657/f110d53e-daf5-11e5-8b26-0275d68a4bc0.png)

*_Some details: *_
text isn't translated: You can also choose a ressource directly from Modx-tree.
(typo: _resource_ and _MODX-tree_)

_Modx-Internal_ needs to be _MODX internal_? and also be translated?

**Comment by fourroses666** [comment]
Ah I see that translation is already in the lang file. I will update that ! I have made a pull

**Comment by fourroses666** [comment]
Ah I see you can select internal link but its not showing any links. Is that a bug?
I can imagine clients don't understand it that good thow. It does help you can select resources but thats not working.

![untitled-1](https://cloud.githubusercontent.com/assets/523389/13285949/64781ab6-dafe-11e5-94b9-8ae8eca8a179.png)

Maybe make a seperate option is better?

![separate-option](https://cloud.githubusercontent.com/assets/523389/13285995/ba0a4760-dafe-11e5-84a2-e4524a01bb4f.png)

I do starting to like this editor allot.

**Comment by Deesen** [comment]
I like the Revo-style link-search also a lot and I think its the best option. Will try to add this feature in future.

Reg. links: The linktype is given by CKEditor by default. "URL" means `<a href="http://">`, "interne link" means `<a href="#anchor">` and email means `<a href="mailto:">`. If you choose anchor, there must be anchors already existing in content.

For internal links you need to leave "Protokoll" to "Interne MODX pagina", this avoids CKEditor prepending a `/` or anything else so the link will result just in `[~1~]`, not in `http://[~1~]`.

**Comment by fourroses666** [comment]
Ah, yea Search like tinymce4 has would be nice. 
Really need to have these links to keep working after moving a resource.
