### ISSUE TITLE
CKeditor config.js not working

### ISSUE THREAD

**Issue by noizo** [Deesen/ckeditor4-modx-evo#5]
sorry, found settings!

**Comment by Deesen** [comment]
:+1:

**Comment by noizo** [comment]
I have to thank You for this great job!
I was waiting for this plugin.
Finally!

**Comment by Deesen** [comment]
You´re welcome! I recommend to create your own theme...php-file so by next update nothing gets overwritten.

**Comment by noizo** [comment]
Ohh, ok. Thanks for advise.
Keep it going!

**Comment by Deesen** [comment]
I did LOL:
https://github.com/modxcms/evolution/pull/548
https://github.com/extras-evolution/tinymce4-for-modx-evo/pull/1#issuecomment-196080437
